### ISSUE TITLE
Can't compile aiostratum-proxy

### ISSUE THREAD

**Issue by stasxpulse** [wetblanketcc/aiostratum_proxy#3]
Hi,
Could you please help to solve this issue:

[root@zecproxy aiostratum_proxy]# pip --version
**pip 18.0** from /usr/lib/python3.4/site-packages/pip (python 3.4)

**[root@zecproxy aiostratum_proxy]# bin/pip install aiostratum-proxy
Collecting aiostratum-proxy
  Could not find a version that satisfies the requirement aiostratum-proxy (from versions: )
No matching distribution found for aiostratum-proxy
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@zecproxy aiostratum_proxy]#**

**Comment by wetblanketcc** [comment]
> Requires Python 3.5 or greater (built with asyncio using async/await syntax)

As mentioned in the documentation, aiostratum-proxy requires Python 3.5. The message above shows that Python 3.4 is in use.

It would be a non-trivial effort to support Python 3.4, sorry! 😞 Closing.

**Comment by stasxpulse** [comment]
looks like I bypass current issue, but bumped into next one.

[root@zecproxy aiostratum_proxy]# pip install aiostratum-proxy
You are using pip version 7.1.0, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting aiostratum-proxy
  Using cached https://files.pythonhosted.org/packages/c1/ec/f412fc36c72929849e78cd4f84ef63bae07f4f74d736381fc46e676a136a/aiostratum_proxy-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-KyiRuu/aiostratum-proxy/setup.py", line 4, in <module>
        import aiostratum_proxy
      File "aiostratum_proxy/__init__.py", line 4, in <module>
        logger.addHandler(logging.NullHandler())
    AttributeError: 'module' object has no attribute 'NullHandler'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KyiRuu/aiostratum-proxy

**Comment by stasxpulse** [comment]
I installed Python 3.5 but now i got something different.
Do you have an idea what might be wrong?

[root@zecproxy aiostratum_proxy]# pip install aiostratum-proxy
You are using pip version 7.1.0, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting aiostratum-proxy
  Using cached https://files.pythonhosted.org/packages/c1/ec/f412fc36c72929849e78cd4f84ef63bae07f4f74d736381fc46e676a136a/aiostratum_proxy-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-KyiRuu/aiostratum-proxy/setup.py", line 4, in <module>
        import aiostratum_proxy
      File "aiostratum_proxy/__init__.py", line 4, in <module>
        logger.addHandler(logging.NullHandler())
    AttributeError: 'module' object has no attribute 'NullHandler'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KyiRuu/aiostratum-proxy

**Comment by jaddison** [comment]
I am unfamiliar with CentOS, but it certainly looks like something is misconfigured. Research shows me that `NullHandler` exists in Python>=2.7 and Python>=3.1.

Can you run the following commands and show me the output? All output should mention Python3.5, if that is your system default Python.
```
pip --version
python --version
```

Also, [use Python virtual environments](https://github.com/wetblanketcc/aiostratum_proxy#installation) if you are not already.

**Comment by wetblanketcc** [comment]
I am unfamiliar with CentOS, but it certainly looks like something is misconfigured. Research shows me that `NullHandler` exists in Python>=2.7 and Python>=3.1.

Can you run the following commands and show me the output? All output should mention Python3.5, if that is your system default Python.
```
pip --version
python --version
```

Also, [use Python virtual environments](https://github.com/wetblanketcc/aiostratum_proxy#installation) if you are not already.

**Comment by stasxpulse** [comment]
Hi,

Here is output from commands you mentioned.

[root@zecproxy ~]# pip --version
pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)
[root@zecproxy ~]# python --version
Python 3.5.5

For some reason pip is still using python2.6 instead 3.5.5

**Comment by wetblanketcc** [comment]
I suspect if you use the Python3 virtual environments as suggested in the docs, things will work better for you.
```
python3 -m venv aiostratum_proxy
```
See more at https://docs.python.org/3.5/library/venv.html.

**Comment by stasxpulse** [comment]
For some reason where it no pip in /bin folder after running this command, only python


________________________________

**Comment by wetblanketcc** [comment]
Again, I don't know CentOS at all, but use the method you used  to install python3.5 to install pip for python3. I assume there are many articles written for installing a complete Python3.5+ setup on CentOS. 

A little googling reveals https://linuxhint.com/install-python-pip-centos7/, but I'm not sure if that's entirely relevant. I hope it gets you on the right track!
